# Generated by Django 4.0.2 on 2022-02-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_product_added_to_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Ratings',
            field=models.CharField(default='0/5', max_length=264),
        ),
    ]
