# Generated by Django 4.0.2 on 2022-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0004_alter_product_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Ratings',
            field=models.TextField(default='0/5', max_length=100, verbose_name='Rating'),
        ),
    ]
